# action.yml
name: 'Db'
description: 'spin-up a postgres db'
inputs:
  db:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'postgres'
  args:
    - ${{ inputs.db }}
    - 'POSTGRES_PASSWORD:hello'